// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BowlingGame.Data.Data;

public partial class Player
{
    public int PlayerId { get; set; }

    public string PlayerName { get; set; }

    public virtual ICollection<Frame> Frames { get; set; } = new List<Frame>();
}