// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BowlingGame.Data.Data;

public partial class Frame
{
    public int FrameId { get; set; }

    public int FirstScore { get; set; }

    public int? SecondScore { get; set; }

    public int? ThirdScore { get; set; }

    public string FrameResult { get; set; }

    public int TotalScore { get; set; }

    public int GameId { get; set; }

    public int PlayerId { get; set; }

    public virtual Game Game { get; set; }

    public virtual Player Player { get; set; }
}