// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BowlingGame.Data.Data;

public partial class Game
{
    public int GameId { get; set; }

    public DateTime GameDate { get; set; }

    public virtual ICollection<Frame> Frames { get; set; } = new List<Frame>();
}