// <auto-generated> This file has been generated by Gccg on 2023-10-22 오후 8:31:31. </auto-generated>
#region using
using System.Collections.Generic;
using System.Linq;
#endregion

namespace BowlingGame.Data.Data;

public partial class EntityDao<T>
{
    protected virtual partial void OnSaved(T entity, LogType logType)
    {
        // TODO : 엔티티의 로그를 기록한다.
    }

    protected virtual partial void OnSaved(IEnumerable<T> entities, LogType logType)
    {
        // TODO : 엔티티의 로그를 기록한다.
    }
}