// <auto-generated> This file has been generated by Gccg on 2023-10-22 오후 8:31:31. </auto-generated>
#region using
using System.Collections.Generic;
using System.Linq;
#endregion

namespace BowlingGame.Data.Data;


public partial class FrameDao
{
}

