// <auto-generated> This file has been generated by Gccg on 2023-10-22 오후 8:31:31. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace BowlingGame.Data.Data;

public partial class Entity<T>
{
    public partial void WriteAuditInfo()
    {
		// TODO : 객체에 감사정보를 기입한다. 보통 ModifiedAt, ModifiedBy 등의 속성을 기록함.
    }
}
