
// <auto-generated> This file has been generated by Gccg on 2023-10-22 오후 8:31:31. </auto-generated>
#region using
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
 
#endregion

namespace BowlingGame.Data.Data;


#region FrameMetadata
public class FrameMetaData
{
    public int FrameId {get; set;} 
		public int FirstScore {get; set;} 
		public string FrameResult {get; set;} 
		public int GameId {get; set;} 
		public int PlayerId {get; set;} 
		public int? SecondScore {get; set;} 
		public int? ThirdScore {get; set;} 
		public int TotalScore {get; set;} 
	
	// The key type(s) is/are 
	// int _FrameId {get; set;} 
}
#endregion

[MetadataType(typeof(FrameMetaData))]
public partial class Frame
{
}

